### ISSUE TITLE
Shared Kotlin can't find Reaktive

### ISSUE THREAD

**Issue by ethanjdiamond** [badoo/Reaktive#150]
Hi Arkadii and Dmitry,

Thanks for your hard work on this! I think it's going to be great.

Sorry if this question is due to my unfamiliarity with Gradle instead of a bug on your end. I'm trying to add `com.badoo.reaktive:reaktive:1.0.0-beta1` as a dependency for the shared Kotlin layer for [my multiplatform experiment here](https://github.com/ethanjdiamond/kotlin-mp-sample).

I've added it as a dependency [here](https://github.com/ethanjdiamond/kotlin-mp-sample/blob/master/Shared/build.gradle), and am trying to import Reaktive [here](https://github.com/ethanjdiamond/kotlin-mp-sample/blob/master/Shared/common/src/components/root/RootBuilder.kt) but when I try to run it, it says `Unresolved reference "com"` which means my `import com.badoo.reaktive.*` is failing.

Do you know what I'm doing wrong here?

Thanks!

**Comment by arkivanov** [comment]
Hey! Thanks for the feedback! I have poked your sample and found multiple mistakes:

- Folder structure is wrong, it should be `Shared/src/commonMain/kotlin/components/root`, in your sample it is `Shared/common/src/components/root`. The root folder for sources in every module should be `src`. Then there should be folders for source sets: `commonMain`, `commonTest`, `androidMain`, `androidTest`, etc. Then folder named `kotlin`. And then your packages with code.
- You can remove `kotlin { srcDirs = ... }` from you `build.gradle` files
- Each Kotlin source file should start with `package ...` line, please add `package components.root` as a first line into your `RootBuilder.kt` file.

Should you have any other questions then don't hesitate to ask them. If the problem is solved then please close the issue. Thanks!

**Comment by arkivanov** [comment]
Also I'm not sure whether you are familiar with the Kotlin Native memory model restrictions or not, but just in case I will post some useful links to avoid confusion when you your first multiplatform code: [K/N Concurrency](https://kotlinlang.org/docs/reference/native/concurrency.html) [K/N Immutability](https://kotlinlang.org/docs/reference/native/immutability.html).

**Comment by ethanjdiamond** [comment]
Thanks for the feedback! My question was more specifically about why I can’t import com.badoo.reaktive.* in RootBuilder. Are you saying it’s because I’ve made a mistake in my folder structure?

Thanks,
Ethan

**Comment by arkivanov** [comment]
Exactly, please apply the suggestions.

**Comment by ethanjdiamond** [comment]
It looks like it was because com.badoo.reaktive.* wasn't specific enough. Doing com.badoo.reaktive.observable.* works.

Thanks for the help!
