### ISSUE TITLE
Empty constructor for BehaviorSubject

### ISSUE THREAD

**Issue by vchernyshov** [badoo/Reaktive#438]
There is any opportunity to add constructor without initial value for BehaviorSubject like in RxRelay?

**Comment by arkivanov** [comment]
@vchernyshov Thanks for the question.

This was an explicit design decision. In RxJava `null` values are not allowed, however `BehaviorSubject.getValue()` method returns nullable value. When you initialize a `BehaviorSubject` without initial value then `getValue()` will return null. If you subscribe to such a `BehaviorSubject` then you will not receive any values unless first value is supplied.

In Reaktive `null` values are allowed because Kotlin has its strict nullability checks at compile time. So you can just create it like this: `BehaviorSubject<String?>(null)`. 

You can filter null values if you don't need them:
```kotlin
    val subject = BehaviorSubject<String?>(null)
    subject.notNull().subscribe {  }
```

**Comment by vchernyshov** [comment]
@arkivanov Thanks a lot for you detailed answer)
