### ISSUE TITLE
Question: how to correctly use Ktor inside singeFromCoroutine?

### ISSUE THREAD

**Issue by xirdneh** [badoo/Reaktive#478]
According to the [docs](https://github.com/badoo/Reaktive#coroutines-interop) one shouldn't use Ktor inside `singleFromCoroutine`
Is this still true for production? If so, then, where should I implement the suggested `singleFromCoroutineUnsafe` or what are the other options y'all suggest?

This is how I'm creating an observable from a Ktor call:

```kotlin
    override val loading: Observable<Boolean>
    override val result: Observable<List<Item>>

    private val mListProperty: PublishSubject<Int> = PublishSubject()
    private val mLoadMoreProperty: PublishSubject<Int> = PublishSubject()

    init {
        val loadingProperty: PublishSubject<Boolean> = PublishSubject()
        val items = mutableListOf<Item>()
        var clearItems = false
        loading = loadingProperty

        val initialRequest = mListProperty
            .doOnBeforeNext { loadingProperty.onNext(true) }
            .flatMapSingle { page ->
                singleFromCoroutine { useCase.execute() // create httClient and do http call }
                    .subscribeOn(ioScheduler)
            }
            .observeOn(mainScheduler)
            .doOnBeforeNext {
                loadingProperty.onNext(false)
                clearItems = true
            }

        val nextRequest = mLoadMoreProperty
            .doOnBeforeNext { loadingProperty.onNext(true) }
            .flatMapSingle { page ->
                singleFromCoroutine { useCase.execute(page) // create httpClient and use}
                    .subscribeOn(ioScheduler)
            }
            .doOnBeforeNext {
                loadingProperty.onNext(false)
                clearItems = false
            }

        result = merge(initialRequest, nextRequest).map {
            if (clearItems) {
                items.clear()
            }

            items.addAll(it)

            items
        }
    }
```

And then on my activity I'm subscribing to the `result` observable like so:
```kotlin
binding.subscribe(viewModel.output.result.subscribeOn(ioScheduler), onNext = ::result)
```
any feedback would be appreciated, thanks!

**Comment by arkivanov** [comment]
Hello, thanks for your question. The statement about Ktor is valid only for Kotlin/Native, and will remain valid until [multi-threaded coroutines](https://github.com/kotlin/kotlinx.coroutines/issues/462) are available. You mentioned "activity" so I assume you are using Android. In this case everything should be fine with Ktor and Reaktive coroutines interoperability.

**Comment by xirdneh** [comment]
@arkivanov Ok, but I am in the process of sharing this code in an iOS app, too.
When you say Kotlin/native, you're referring to iOS or which context is Kotlin/native?

**Comment by arkivanov** [comment]
@xirdneh By Kotlin/Native I mean any K/N target, they all listed [here](https://kotlinlang.org/docs/reference/native-overview.html#target-platforms). 

So current stable version of coroutines does not work well in multi-threaded environment in K/N, e.g. `Job` can not be frozen. The proper way to run coroutine in a background thread is to use `runBlocking`, this is what Reaktive does. This limitation has one very important impact - subscription to a `xxxFromCoroutine` is _blocking_, so `subscribeOn(<any background scheduler>)` must be used.

Next, currently Ktor crashes heavily if used in a background thread in K/N. In other words it should be used only on main thread. This is not a problem if you use plain coroutines, since Ktor calls are suspending and so do not block the main thread. But if you need multi-threading (e.g. for parsing or disk access) then this might be a problem.

So there are two recommendations currently:

1. If you _really_ need to use Ktor, then you can try the [unsafe solution](https://github.com/badoo/Reaktive#coroutines-interop) described in the Readme, but make sure you are not switching threads;
2. Otherwise I recommend to avoid using Ktor currently and replace it with expect/actual, in most cases it should be simple ([Android sample](https://github.com/badoo/Reaktive/blob/master/sample-mpp-module/src/jvmCommonMain/kotlin/com/badoo/reaktive/samplemppmodule/KittenLoaderImpl.kt), [iOS sample](https://github.com/badoo/Reaktive/blob/master/sample-mpp-module/src/darwinCommonMain/kotlin/com/badoo/reaktive/samplemppmodule/KittenLoaderImpl.kt)).

All of the above applies only to Kotlin/Native.

**Comment by xirdneh** [comment]
Awesome! Thanks for the response and suggestions.
Great work on the library, congrats :)
