### ISSUE TITLE
ArrayDeque

### ISSUE THREAD

**Issue by CherryPerry** [badoo/Reaktive#529]
Use [ArrayDeque](https://kotlinlang.org/docs/reference/whatsnew14.html#arraydeque) from stdlib instead of [our own implementation](https://github.com/badoo/Reaktive/blob/master/reaktive/src/commonMain/kotlin/com/badoo/reaktive/utils/queue/ArrayQueue.kt)?

Features are the same:
- Backed by array
- removeFirstOrNull = poll
- add = offer

**Comment by CherryPerry** [comment]
Is it? Do not see any marks about it. [Docs](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/-array-deque/).

**Comment by arkivanov** [comment]
Probably it is not stable, so we can use it.

**Comment by arkivanov** [comment]
Probably we will also need to change the `Queue` interface so it will match the `ArrayDeque` and so we could `typealias` it.

**Comment by arkivanov** [comment]
@CherryPerry It is not so easy to use `ArrayDeque` from stdlib. Because we have `Queue` interface and two implementations of it: `ArrayQueue` and `PriorityQueue`. `ArrayDeque` don't have any special `Queue` interface, it implements `MutableList`.
We already have `ArrayQueue` implemented and covered, let's keep it for now?

**Comment by CherryPerry** [comment]
No objections
