### ISSUE TITLE
Could not find com.badoo.reaktive:coroutines-interop:1.2.2-nmtc

### ISSUE THREAD

**Issue by rickytribbia** [badoo/Reaktive#678]
Is it `x.x.x-nmtc` still needed to use reaktive coroutines interop with new memory model?

If yes, I notice that 1.2.2-nmtc couldn't be found. 

Thank you for your work

**Comment by arkivanov** [comment]
Indeed, we forgot to publish `1.2.2-nmtc`. It's still needed for the new memory model, thanks for raising it. I will prepare the `mt-coroutines` branch for the release today.

cc/ @CherryPerry

**Comment by CherryPerry** [comment]
@arkivanov When 1.7.20 is released I can merge `mt-coroutines` in the main branch, right?

**Comment by arkivanov** [comment]
@CherryPerry As mentioned in this [comment](https://github.com/Kotlin/kotlinx.coroutines/issues/462#issuecomment-999557659), they are gradually stopping support of the `native-mt` coroutines in coroutines `v1.6.x`, and the support will be stopped completely in coroutines `v1.7.0`. Indeed, since Kotlin `1.7.20` the new memory model will be enabled by default, and there will be a way to opt-out. Merging `mt-coroutines` into the main branch would be a massive breaking change for users still on the old memory model for whatever reason.

I've been thinking about merging `mt-corotunes` into the main branch, and at the same time removing the support of the old memory model in Reaktive `v2.0.0`. This should boost performance further on all platforms. There is a todo item in #620. I will be working on `v2.0.0` soon. Does it sound reasonable?

**Comment by CherryPerry** [comment]
Released, should be available soon.
